/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerStats = IDL.Record({
  'highestLevel' : IDL.Nat,
  'highestScore' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const Type__1 = IDL.Variant({
  'playing' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
});
export const RoomState = IDL.Record({
  'status' : Type__1,
  'score1' : IDL.Nat,
  'score2' : IDL.Nat,
  'player1' : IDL.Text,
  'player2' : IDL.Opt(IDL.Text),
  'level1' : IDL.Nat,
  'level2' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const Type = IDL.Variant({
  'win' : IDL.Null,
  'draw' : IDL.Null,
  'lose' : IDL.Null,
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
  'getRoomState' : IDL.Func([IDL.Text], [RoomState], ['query']),
  'getTopLeaderboardScores' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitLeaderboardScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitRobotBattleResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, Type],
      [],
      [],
    ),
  'updatePlayerStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateRoomScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerStats = IDL.Record({
    'highestLevel' : IDL.Nat,
    'highestScore' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const Type__1 = IDL.Variant({
    'playing' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const RoomState = IDL.Record({
    'status' : Type__1,
    'score1' : IDL.Nat,
    'score2' : IDL.Nat,
    'player1' : IDL.Text,
    'player2' : IDL.Opt(IDL.Text),
    'level1' : IDL.Nat,
    'level2' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const Type = IDL.Variant({
    'win' : IDL.Null,
    'draw' : IDL.Null,
    'lose' : IDL.Null,
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
    'getRoomState' : IDL.Func([IDL.Text], [RoomState], ['query']),
    'getTopLeaderboardScores' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitLeaderboardScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitRobotBattleResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, Type],
        [],
        [],
      ),
    'updatePlayerStats' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateRoomScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };