/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry { 'score' : bigint, 'playerName' : string }
export interface PlayerStats {
  'highestLevel' : bigint,
  'highestScore' : bigint,
  'totalGames' : bigint,
}
export interface RoomState {
  'status' : Type__1,
  'score1' : bigint,
  'score2' : bigint,
  'player1' : string,
  'player2' : [] | [string],
  'level1' : bigint,
  'level2' : bigint,
}
export type Type = { 'win' : null } |
  { 'draw' : null } |
  { 'lose' : null };
export type Type__1 = { 'playing' : null } |
  { 'finished' : null } |
  { 'waiting' : null };
export interface _SERVICE {
  'createRoom' : ActorMethod<[string], string>,
  'getPlayerStats' : ActorMethod<[], PlayerStats>,
  'getRoomState' : ActorMethod<[string], RoomState>,
  'getTopLeaderboardScores' : ActorMethod<[], Array<LeaderboardEntry>>,
  'joinRoom' : ActorMethod<[string, string], undefined>,
  'submitLeaderboardScore' : ActorMethod<[string, bigint], undefined>,
  'submitRobotBattleResult' : ActorMethod<
    [string, bigint, bigint, Type],
    undefined
  >,
  'updatePlayerStats' : ActorMethod<[bigint, bigint], undefined>,
  'updateRoomScore' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];